language: node_js
node_js:
- '0.10'
git:
  depth: 10
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: MxZC1rKyH5G7S0NZQ9CAE8hkARbi6VaRC6jxDlws9zNwEcoRj19iptBwkJacRU0+O5pX3pkJhV/MB/cVxnfn7BKukWCdkG2/cuYbhY6fLgnmTOJppQI98iiIGXWayx2Z4e4Bfb5FkmSNDD2K+PnV3QhPfAbfQw6k1gJX7dwhKYozRdSZFbn/MJNZD7oymhiXqTZamC3ckgaxq94o0izZONu3sU9s9KDNKVZmiieDHnyIKaQbUure5EE+K3WG3kjpmjKenTQZuJ8oCkTCqD2IVJKPwOqU1Wo84zANzZNPtgXVuYFbeRxbgXrWEc56c+6zOcswp09c3xeiyr0KH/fsnrhJnHiR/e0NPkcEfQXt9mTzeZFP2F8+xOCcJLaZxo4OhMOUah8Mz2Ku7b9tV/VLPJFxHtD0dUD9TdKmago2HihBcOh2pYk8x8elpHs11ecBa5LXTEgVzxr/FNcIxZLaPT+Tt6f0k6/8NTOJyMjFf13Av07TGrtI160qzyGzYOtjixwEr5Wm3/xkodJ6nQh00n8cuSB/7h+BzCoNinojbDQooDPeU608Ysfjgw3or6i8Jy5YTlggI7Z2TdivAg36OZyVPHIbhSwv+9lCAE2XFo4db8qIjk7UZ9qGDgrI9yy85xfQIrJ8yEldCisbYDYKP1m+jhuRD1/qlvGw2Z+g4XY=
  on:
    tags: true
    repo: angular-ui/ui-mask
